//[
//	{
//		composition: ['Тюльпаны', 'Хризантемы', 'Лилия'],
//		currentPrice: '4050',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'D163688197',
//		images: 'images/product-prada.jpg',
//		oldPrice: '5500',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '50',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Букет Prada',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '4050',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'D453587083',
//		images: 'images/product-mindal.jpg',
//		oldPrice: '6500',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '80',
//			sizes: ['mini', 'standart'],
//			width: '35',
//		},
//		sendPerson: 'Подруге',
//		title: 'Роза "Мондиаль" 60см 25шт с эвкалиптом ',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '4150',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'K722135520',
//		images: 'images/product-malina.jpg',
//		oldPrice: '2370',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '35',
//		},
//		title: '9 малиновых кустовых роз в упаковке ',
//		preOrder: true,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '1800',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'K900950931',
//		images: 'images/product-mix.jpg',
//		oldPrice: '2600',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '40',
//			sizes: ['mini', 'standart'],
//			width: '35',
//		},
//		title: 'Букет 25 роз Нежный микс',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '3150',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'P602168936',
//		images: 'images/product-silver.jpg',
//		oldPrice: '4000',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '50',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Сильвер 15 роз',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '3900',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'S681685154',
//		images: 'images/product-box-flowers.jpg',
//		oldPrice: '4500',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Коробка с цветами №20',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '3150',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'U249713528',
//		images: 'images/product-iris.jpg',
//		oldPrice: '4250',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '45',
//			sizes: ['mini', 'standart'],
//			width: '35',
//		},
//		title: 'Букет 35 желтых тюльпанов и ирисов',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '1800',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'Z147822665',
//		images: 'images/product-nightingale.jpg',
//		oldPrice: '2500',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '45',
//			sizes: ['mini', 'standart'],
//			width: '35',
//		},
//		title: '25 сиреневых роз Nightingale 40 см. ',
//		preOrder: true,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '3250',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'c261840444',
//		images: 'images/product-nina.jpg',
//		oldPrice: '3750',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Роза "Нина" 50 см 25 шт.',
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '3000',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'e171365908',
//		images: 'images/product-81.jpg',
//		oldPrice: '4250',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '50',
//			sizes: ['mini', 'standart'],
//			width: '30',
//		},
//		title: 'Сборный букет №81 размер М',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '9800',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'f546604763',
//		images: 'images/product-usual.jpg',
//		oldPrice: '11000',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '30',
//		},
//		title: 'Букет кустовых и обычных роз микс ',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '2800',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'h356462174',
//		images: 'images/product-diant.jpg',
//		oldPrice: '3250',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Букет розовых диантусов № 2',
//		preOrder: false,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '2350',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'j613830731',
//		images: 'images/product-spring.jpg',
//		oldPrice: '3200',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '40',
//			sizes: ['mini', 'standart'],
//			width: '30',
//		},
//		title: 'Весна пришла',
//		preOrder: true,
//	},
//	{
//		composition: ['Тюльпаны', 'Хризантемы'],
//		currentPrice: '2750',
//		descr: 'Нежный, насыщенный и ароматный букет белых альстромерий, лавандовых роз и сантини. ',
//		id: 'l670357696',
//		images: 'images/product-dream.jpg',
//		oldPrice: '3150',
//		options: {
//			colors: ['red', 'yellow', 'white'],
//			diameter: '42',
//			height: '60',
//			sizes: ['mini', 'standart'],
//			width: '40',
//		},
//		title: 'Букет "Тайная мечта "',
//		preOrder: false,
//	},
//];
